---
name: "Zeek-Kafka CI"

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        platform: [Ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run linting
        run: make lint
  e2e:
    strategy:
      matrix:
        platform: [Ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: cache-docker
        uses: actions/cache@v2
        with:
          path: ~/cache
          key: ${{ runner.os }}-cache
      - name: Run e2e tests
        run: |
          if [[ -f ~/cache/docker.tar ]]; then
            echo "Loading ~/cache/docker.tar..."
            docker load --input ~/cache/docker.tar
          fi && \
          make e2e
      - name: Update docker cache
        run: |
             mkdir -p ~/cache && \
             images=($(ls -1 docker/containers | awk '{print "zeek-kafka_" $0}')) && \
             docker save ${images[*]} -o ~/cache/docker.tar || true
